export const ICONS = {
  logo: require('../../assets/icons/logo.png'),
  event_active: require('../../assets/icons/event_active.png'),
  event_inactive: require('../../assets/icons/event_inactive.png'),
  favorite_inactive: require('../../assets/icons/favorite_inactive.png'),
  favorite_active: require('../../assets/icons/favorite_active.png'),
  profile_inactive: require('../../assets/icons/profile_inactive.png'),
  search_inactive: require('../../assets/icons/search_inactive.png'),
  hide: require('../../assets/icons/hide.png'),
  view: require('../../assets/icons/view.png'),
  image: require('../../assets/icons/image.png'),
  facebook: require('../../assets/icons/facebook-logo.png'),
  google: require('../../assets/icons/google-logo.png'),
  apple: require('../../assets/icons/apple-logo.png'),
  arrow_right: require('../../assets/icons/arrow-right.png'),
  share: require('../../assets/icons/share.png'),
  favorite: require('../../assets/icons/heart-filled.png'),
  unfavorite: require('../../assets/icons/heart-outline.png'),
};
